### ISSUE TITLE
About the data in ModaNet

### ISSUE THREAD

**Issue by tangshixiang** [xushilin1/FashionFormer#12]
Hi,

I find ModaNet hard to download. I would like to know whether there is some easy way to get the ModaNet datasets. Or could you provide a zip file of ModaNet?

Best regards,

TANG, shixiang

**Comment by xushilin1** [comment]
I got the ModatNet dataset according to the official tutorial. It is not convenient for me to provide the original data. You can try it on other datasets.

Sorry for that!
