### ISSUE TITLE
About project license

### ISSUE THREAD

**Issue by PaulohFerreira** [xushilin1/FashionFormer#15]
Hello folks, that’s a really nice project! I would like to use it in one of my projects, but I saw that this repository don’t have any license file. Do you folks intend to add some open source licensing in this project, or should we assume that the code published here can’t be used in other places?

Thank you 😄

**Comment by xushilin1** [comment]
Thanks for your interest in our project. This project will adopt Apache License 2.0, and you can use the code under the license.
Thanks!
